### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Haizanjs** [smefcc/smef-s-Indigo-Remasterd#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1696	cannot open source file "d3dx9.h"	INDIGO	f:\Downloads\cs\smef-s-Indigo-Remasterd-master\INDIGO\Main\Main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Client.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Backtrack\LagComp.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Misc\Misc.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Aimbot\Aimbot.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Esp\Esp.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Radar\Radar.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Skin\DynSkin.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Skin\Skin.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Cheat\Triggerbot\Triggerbot.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Engine.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Hook.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\NetVar.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Entity.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Offset.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Render.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Players.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Engine\Weapon.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file License\License.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Main\Main.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18	
Error	C1083	Cannot open include file: 'd3dx9.h': No such file or directory (compiling source file Settings\Settings.cpp)	INDIGO	f:\downloads\cs\smef-s-indigo-remasterd-master\indigo\main\main.h	18

**Comment by NuclearC** [comment]
Install DirectX SDK 2010. Download it from here https://www.microsoft.com/en-us/download/details.aspx?id=6812. Add DirectX SDK Include directories into project's additional include directories. And dont forget to link against SDK's libraries
