### ISSUE TITLE
Backtrack not working

### ISSUE THREAD

**Issue by Gaming12846** [smefcc/smef-s-Indigo-Remasterd#22]
My Backtrack is not working and the DrawBacktrack too.

**Comment by smefcc** [comment]
"Jozkah - Today at 2:33 PM
lmao
It is working"

**Comment by Gaming12846** [comment]
but not on 64ticks server

**Comment by smefcc** [comment]
// being looked into

**Comment by Gaming12846** [comment]
Backtrack is fixed but Draw Backtrack Ticks dont work

**Comment by Gaming12846** [comment]
Thx its working fine!
