### ISSUE TITLE
Fps Drop while using cheat build from source

### ISSUE THREAD

**Issue by trongtinh1212** [smefcc/smef-s-Indigo-Remasterd#3]
I have both version Remasterd and Original but all the same , drop fps all the time, I don't know why

**Comment by molendus1001** [comment]
This cheat renders on overlay, instead of rendering directly in game process, which makes it 'obs-proof'
Rendering in overlay is more hardware intensive.

**Comment by trongtinh1212** [comment]
how to optimize this ? can u help me xD

**Comment by trongtinh1212** [comment]
optimize the source code with VS, done !
