### ISSUE TITLE
Want to thank you!

### ISSUE THREAD

**Issue by Floraly** [smefcc/smef-s-Indigo-Remasterd#5]
I have reviewed your copy and i fixed many errors and deleted many unused Code. Now I have got clean base for new Projects with Protobuf which is really interesting! It is really nice to see things in work and making new stuff with it. I have many ideas!

If you want the fixed sources + VAC undetected injector mail PM!

**Comment by DelaiRz** [comment]
Is it possible for me to get a copy of this? @Floraly
